# Build the docker container and push it to the GitLab Container Registry
# Always use the CI_COMMIT_REF_NAME for image tagging, because the CI_ENVIRONMENT_SLUG might not exist in this stage.
# Source: https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
.build-and-push-container:
 image:
   name: gcr.io/kaniko-project/executor:debug
   entrypoint: [""]
 script:
   - echo "Building and pushing the image to $CI_REGISTRY_IMAGE"
   - mkdir -p /kaniko/.docker
   - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
   - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME $ADDLATESTTAG $FORMATTEDTAGLIST $IMAGE_LABELS --label build-date=`date -Iseconds`
